base:
  base_dir: '../runs/'
  experiment: 'std'
dataset:
  pth: '/home1/quanquan/datasets/Cephalometric/'
training:
  batch_size : 8
  num_workers : 8
  num_landmarks : 19
  lr : 0.00001
  decay_step : 50
  decay_gamma : 0.8
  num_epochs : 1280
  save_seq : 100
  nearby : 6
  lambda : 2
  alpha : 0.99
  non_local: True
  conf: False
  patch_size: 256